CREATE TABLE Tags (ID INTEGER PRIMARY KEY, Name char(300));
CREATE TABLE Persons (ID INTEGER PRIMARY KEY, Name char(200));
CREATE TABLE Resources (ID INTEGER PRIMARY KEY, Type char(20), Name char(1024), LastUse DATETIME);
CREATE TABLE Email (ID INTEGER PRIMARY KEY, EntryID char(200), ConversatioID char(100));
CREATE TABLE ResourceTags (ID INTEGER PRIMARY KEY, ResourceID INTEGER, TagID INTEGER);
CREATE TABLE PersonTags (ID INTEGER PRIMARY KEY, PersonID INTEGER, TagID INTEGER);
CREATE TABLE EmailTags (ID INTEGER PRIMARY KEY, EmailID INTEGER, TagID INTEGER);
CREATE TABLE DocumentsReceived (ID INTEGER PRIMARY KEY, PersonID INTEGER, ResourceID INTEGER);
CREATE TABLE DocumentsSent (ID INTEGER PRIMARY KEY, PersonID INTEGER, ResourceID INTEGER);
CREATE TABLE EmailReceived (ID INTEGER PRIMARY KEY, PersonID INTEGER, EmailID INTEGER);
CREATE TABLE EmailSent (ID INTEGER PRIMARY KEY, PersonID INTEGER, EmailID INTEGER);







