CREATE TABLE Tags (ID INTEGER PRIMARY KEY AUTOINCREMENT, Name char(300));
CREATE TABLE Persons (ID INTEGER PRIMARY KEY AUTOINCREMENT, Name char(200));
CREATE TABLE Resources (ID INTEGER PRIMARY KEY AUTOINCREMENT, Type char(20), Name char(1024), LastUse DATETIME);
CREATE TABLE Emails (ID INTEGER PRIMARY KEY AUTOINCREMENT, EntryID char(200), ConversationID char(100));
CREATE TABLE ResourceTags (ID INTEGER PRIMARY KEY AUTOINCREMENT, ResourceID INTEGER, TagID INTEGER);
CREATE TABLE PersonTags (ID INTEGER PRIMARY KEY AUTOINCREMENT, PersonID INTEGER, TagID INTEGER);
CREATE TABLE EmailTags (ID INTEGER PRIMARY KEY AUTOINCREMENT, EmailID INTEGER, TagID INTEGER);
CREATE TABLE DocumentsReceived (ID INTEGER PRIMARY KEY AUTOINCREMENT, PersonID INTEGER, ResourceID INTEGER);
CREATE TABLE DocumentsSent (ID INTEGER PRIMARY KEY AUTOINCREMENT, PersonID INTEGER, ResourceID INTEGER);
CREATE TABLE EmailReceived (ID INTEGER PRIMARY KEY AUTOINCREMENT, PersonID INTEGER, EmailID INTEGER);
CREATE TABLE EmailSent (ID INTEGER PRIMARY KEY AUTOINCREMENT, PersonID INTEGER, EmailID INTEGER);







